
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging # テスト用
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: 'info@yuuniworks.com'
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod # 本番用
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'info@yuuniworks.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}