apiVersion: v1
kind: Service
metadata:
  name: travelr-pgadmin-svc # この名前でpodから名前解決できる
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: travelr-pgadmin
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: travelr-pgadmin-dpl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: travelr-pgadmin
    spec:
      volumes:
      - name: volume-travelr-pgadmin
        persistentVolumeClaim:
          claimName: pvc-travelr-pgadmin
      containers:
      - name: travelr-pgadmin
        image: dpage/pgadmin4:3.1
        resources:
          requests:
            cpu: 0
            memory: 0
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "some@dummy.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: travelr_pgadmin4_pass
        volumeMounts:
          - mountPath: "/var/lib/pgadmin"
            name: volume-travelr-pgadmin
        # Ingressのバックエンドとして使うためには必須
        readinessProbe:
          httpGet:
            path: /login?next=%2F
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
---
# pgadmin用PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-travelr-pgadmin
spec:
  storageClassName: ""
  volumeName: pv-travelr-pgadmin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
---
# pgadmin用PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-travelr-pgadmin
spec:
  storageClassName: ""
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  # run following command once before use th disk
  # gcloud compute disks create --size=10GB --zone=asia-northeast1-a --type=pd-standard disk-for-travelr-pgadmin
  gcePersistentDisk:
    pdName: disk-for-travelr-pgadmin
    fsType: ext4
